/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellIndexRouteImport } from './routes/_shell/index'
import { Route as ShellAuthRouteImport } from './routes/_shell/auth'
import { Route as ShellCardsRouteImport } from './routes/_shell/cards'
import { Route as ShellOnlineRouteImport } from './routes/_shell/online'
import { Route as ShellPassPlayRouteImport } from './routes/_shell/pass-play'
import { Route as ShellProfileRouteImport } from './routes/_shell/profile'
import { Route as ShellResetPasswordRouteImport } from './routes/_shell/reset-password'
import { Route as ShellScanRouteImport } from './routes/_shell/scan'
import { Route as ShellAuthCallbackRouteImport } from './routes/_shell/auth_.callback'
import { Route as ShellDotlovableOauthConsentRouteImport } from './routes/_shell/[.]lovable.oauth.consent'
import { Route as ShellOnlineRoomCodeRouteImport } from './routes/_shell/online_.room.$code'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as ApiImageProxyRouteImport } from './routes/api.image-proxy'
import { Route as PlayModeRouteImport } from './routes/play.$mode'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as ApiDeezerSearchRouteImport } from './routes/api.deezer.search'
import { Route as AuthSpotifyCallbackRouteImport } from './routes/auth_.spotify.callback'
import { Route as PlayTrackIdRouteImport } from './routes/play.track.$id'
import { Route as ApiDeezerTrackIdRouteImport } from './routes/api.deezer.track.$id'

const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAuthRoute = ShellAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCardsRoute = ShellCardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => ShellRoute,
} as any)
const ShellOnlineRoute = ShellOnlineRouteImport.update({
  id: '/online',
  path: '/online',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPassPlayRoute = ShellPassPlayRouteImport.update({
  id: '/pass-play',
  path: '/pass-play',
  getParentRoute: () => ShellRoute,
} as any)
const ShellProfileRoute = ShellProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ShellRoute,
} as any)
const ShellResetPasswordRoute = ShellResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => ShellRoute,
} as any)
const ShellScanRoute = ShellScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAuthCallbackRoute = ShellAuthCallbackRouteImport.update({
  id: '/auth_/callback',
  path: '/auth/callback',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDotlovableOauthConsentRoute =
  ShellDotlovableOauthConsentRouteImport.update({
    id: '/.lovable/oauth/consent',
    path: '/.lovable/oauth/consent',
    getParentRoute: () => ShellRoute,
  } as any)
const ShellOnlineRoomCodeRoute = ShellOnlineRoomCodeRouteImport.update({
  id: '/online_/room/$code',
  path: '/online/room/$code',
  getParentRoute: () => ShellRoute,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiImageProxyRoute = ApiImageProxyRouteImport.update({
  id: '/api/image-proxy',
  path: '/api/image-proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayModeRoute = PlayModeRouteImport.update({
  id: '/play/$mode',
  path: '/play/$mode',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDeezerSearchRoute = ApiDeezerSearchRouteImport.update({
  id: '/api/deezer/search',
  path: '/api/deezer/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSpotifyCallbackRoute = AuthSpotifyCallbackRouteImport.update({
  id: '/auth_/spotify/callback',
  path: '/auth/spotify/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayTrackIdRoute = PlayTrackIdRouteImport.update({
  id: '/play/track/$id',
  path: '/play/track/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeezerTrackIdRoute = ApiDeezerTrackIdRouteImport.update({
  id: '/api/deezer/track/$id',
  path: '/api/deezer/track/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/auth': typeof ShellAuthRoute
  '/cards': typeof ShellCardsRoute
  '/mcp': typeof McpRoute
  '/online': typeof ShellOnlineRoute
  '/pass-play': typeof ShellPassPlayRoute
  '/profile': typeof ShellProfileRoute
  '/reset-password': typeof ShellResetPasswordRoute
  '/scan': typeof ShellScanRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/image-proxy': typeof ApiImageProxyRoute
  '/auth/callback': typeof ShellAuthCallbackRoute
  '/play/$mode': typeof PlayModeRoute
  '/.lovable/oauth/consent': typeof ShellDotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/deezer/search': typeof ApiDeezerSearchRoute
  '/auth/spotify/callback': typeof AuthSpotifyCallbackRoute
  '/online/room/$code': typeof ShellOnlineRoomCodeRoute
  '/play/track/$id': typeof PlayTrackIdRoute
  '/api/deezer/track/$id': typeof ApiDeezerTrackIdRoute
}
export interface FileRoutesByTo {
  '/': typeof ShellIndexRoute
  '/auth': typeof ShellAuthRoute
  '/cards': typeof ShellCardsRoute
  '/mcp': typeof McpRoute
  '/online': typeof ShellOnlineRoute
  '/pass-play': typeof ShellPassPlayRoute
  '/profile': typeof ShellProfileRoute
  '/reset-password': typeof ShellResetPasswordRoute
  '/scan': typeof ShellScanRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/image-proxy': typeof ApiImageProxyRoute
  '/auth/callback': typeof ShellAuthCallbackRoute
  '/play/$mode': typeof PlayModeRoute
  '/.lovable/oauth/consent': typeof ShellDotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/deezer/search': typeof ApiDeezerSearchRoute
  '/auth/spotify/callback': typeof AuthSpotifyCallbackRoute
  '/online/room/$code': typeof ShellOnlineRoomCodeRoute
  '/play/track/$id': typeof PlayTrackIdRoute
  '/api/deezer/track/$id': typeof ApiDeezerTrackIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/_shell/': typeof ShellIndexRoute
  '/_shell/auth': typeof ShellAuthRoute
  '/_shell/cards': typeof ShellCardsRoute
  '/_shell/online': typeof ShellOnlineRoute
  '/_shell/pass-play': typeof ShellPassPlayRoute
  '/_shell/profile': typeof ShellProfileRoute
  '/_shell/reset-password': typeof ShellResetPasswordRoute
  '/_shell/scan': typeof ShellScanRoute
  '/_shell/auth_/callback': typeof ShellAuthCallbackRoute
  '/_shell/.lovable/oauth/consent': typeof ShellDotlovableOauthConsentRoute
  '/_shell/online_/room/$code': typeof ShellOnlineRoomCodeRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/image-proxy': typeof ApiImageProxyRoute
  '/play/$mode': typeof PlayModeRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/deezer/search': typeof ApiDeezerSearchRoute
  '/auth_/spotify/callback': typeof AuthSpotifyCallbackRoute
  '/play/track/$id': typeof PlayTrackIdRoute
  '/api/deezer/track/$id': typeof ApiDeezerTrackIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cards'
    | '/mcp'
    | '/online'
    | '/pass-play'
    | '/profile'
    | '/reset-password'
    | '/scan'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/image-proxy'
    | '/auth/callback'
    | '/play/$mode'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/deezer/search'
    | '/auth/spotify/callback'
    | '/online/room/$code'
    | '/play/track/$id'
    | '/api/deezer/track/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cards'
    | '/mcp'
    | '/online'
    | '/pass-play'
    | '/profile'
    | '/reset-password'
    | '/scan'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/image-proxy'
    | '/auth/callback'
    | '/play/$mode'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/deezer/search'
    | '/auth/spotify/callback'
    | '/online/room/$code'
    | '/play/track/$id'
    | '/api/deezer/track/$id'
  id:
    | '__root__'
    | '/_shell'
    | '/_shell/'
    | '/_shell/auth'
    | '/_shell/cards'
    | '/_shell/online'
    | '/_shell/pass-play'
    | '/_shell/profile'
    | '/_shell/reset-password'
    | '/_shell/scan'
    | '/_shell/auth_/callback'
    | '/_shell/.lovable/oauth/consent'
    | '/_shell/online_/room/$code'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/image-proxy'
    | '/play/$mode'
    | '/.mcp/invoke-tool/$tool'
    | '/api/deezer/search'
    | '/auth_/spotify/callback'
    | '/play/track/$id'
    | '/api/deezer/track/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
  McpRoute: typeof McpRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiImageProxyRoute: typeof ApiImageProxyRoute
  PlayModeRoute: typeof PlayModeRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiDeezerSearchRoute: typeof ApiDeezerSearchRoute
  AuthSpotifyCallbackRoute: typeof AuthSpotifyCallbackRoute
  PlayTrackIdRoute: typeof PlayTrackIdRoute
  ApiDeezerTrackIdRoute: typeof ApiDeezerTrackIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/auth': {
      id: '/_shell/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof ShellAuthRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/cards': {
      id: '/_shell/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof ShellCardsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/online': {
      id: '/_shell/online'
      path: '/online'
      fullPath: '/online'
      preLoaderRoute: typeof ShellOnlineRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/pass-play': {
      id: '/_shell/pass-play'
      path: '/pass-play'
      fullPath: '/pass-play'
      preLoaderRoute: typeof ShellPassPlayRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/profile': {
      id: '/_shell/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ShellProfileRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/reset-password': {
      id: '/_shell/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ShellResetPasswordRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/scan': {
      id: '/_shell/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ShellScanRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/auth_/callback': {
      id: '/_shell/auth_/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof ShellAuthCallbackRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/.lovable/oauth/consent': {
      id: '/_shell/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof ShellDotlovableOauthConsentRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/online_/room/$code': {
      id: '/_shell/online_/room/$code'
      path: '/online/room/$code'
      fullPath: '/online/room/$code'
      preLoaderRoute: typeof ShellOnlineRoomCodeRouteImport
      parentRoute: typeof ShellRoute
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/image-proxy': {
      id: '/api/image-proxy'
      path: '/api/image-proxy'
      fullPath: '/api/image-proxy'
      preLoaderRoute: typeof ApiImageProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$mode': {
      id: '/play/$mode'
      path: '/play/$mode'
      fullPath: '/play/$mode'
      preLoaderRoute: typeof PlayModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/deezer/search': {
      id: '/api/deezer/search'
      path: '/api/deezer/search'
      fullPath: '/api/deezer/search'
      preLoaderRoute: typeof ApiDeezerSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth_/spotify/callback': {
      id: '/auth_/spotify/callback'
      path: '/auth/spotify/callback'
      fullPath: '/auth/spotify/callback'
      preLoaderRoute: typeof AuthSpotifyCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/track/$id': {
      id: '/play/track/$id'
      path: '/play/track/$id'
      fullPath: '/play/track/$id'
      preLoaderRoute: typeof PlayTrackIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/deezer/track/$id': {
      id: '/api/deezer/track/$id'
      path: '/api/deezer/track/$id'
      fullPath: '/api/deezer/track/$id'
      preLoaderRoute: typeof ApiDeezerTrackIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ShellRouteChildren {
  ShellIndexRoute: typeof ShellIndexRoute
  ShellAuthRoute: typeof ShellAuthRoute
  ShellCardsRoute: typeof ShellCardsRoute
  ShellOnlineRoute: typeof ShellOnlineRoute
  ShellPassPlayRoute: typeof ShellPassPlayRoute
  ShellProfileRoute: typeof ShellProfileRoute
  ShellResetPasswordRoute: typeof ShellResetPasswordRoute
  ShellScanRoute: typeof ShellScanRoute
  ShellAuthCallbackRoute: typeof ShellAuthCallbackRoute
  ShellDotlovableOauthConsentRoute: typeof ShellDotlovableOauthConsentRoute
  ShellOnlineRoomCodeRoute: typeof ShellOnlineRoomCodeRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellIndexRoute: ShellIndexRoute,
  ShellAuthRoute: ShellAuthRoute,
  ShellCardsRoute: ShellCardsRoute,
  ShellOnlineRoute: ShellOnlineRoute,
  ShellPassPlayRoute: ShellPassPlayRoute,
  ShellProfileRoute: ShellProfileRoute,
  ShellResetPasswordRoute: ShellResetPasswordRoute,
  ShellScanRoute: ShellScanRoute,
  ShellAuthCallbackRoute: ShellAuthCallbackRoute,
  ShellDotlovableOauthConsentRoute: ShellDotlovableOauthConsentRoute,
  ShellOnlineRoomCodeRoute: ShellOnlineRoomCodeRoute,
}

const ShellRouteWithChildren =
  ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
  McpRoute: McpRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiImageProxyRoute: ApiImageProxyRoute,
  PlayModeRoute: PlayModeRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiDeezerSearchRoute: ApiDeezerSearchRoute,
  AuthSpotifyCallbackRoute: AuthSpotifyCallbackRoute,
  PlayTrackIdRoute: PlayTrackIdRoute,
  ApiDeezerTrackIdRoute: ApiDeezerTrackIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
